### ISSUE TITLE
Cllient can't upload

### ISSUE THREAD

**Issue by xushier** [binfalse/docker-webdav#1]
I deployed this container in my Unraid Nas , and i could browser files in browser through this container.

But i couldn't upload files in [Photosync](https://www.photosync-app.com/home.html) on Android , and the Popup Window  said that Internet Server Error or Connection Reset.

I tried to upload files using [CyberDuck](https://cyberduck.io/) on Windows OS , and it said Unexpected response ( 500 Internal Server Error ).

It should be the configuration problem of Apache , because the other webdav containers i used work normally.

I can't configure that , could you help me , please ?

**Comment by xushier** [comment]
I have solved this problem. The reason is that the DavLock path in the first line of the default "default.conf" file is specified incorrectly, causing the DavLock file to fail to be created.

DAVLockDB is specified in the path "/etc/apache2/mods-enabled/dav_fs.conf", like this "DAVLockDB ${APACHE_LOCK_DIR}/DAVLock", the actual value of "${APACHE_LOCK_DIR}" can be in "/etc/apache2/envvars" "Found in, like this "export APACHE_LOCK_DIR=/var/lock/apache2$SUFFIX".

The default DavLock file does not exist, but as long as the path of DavLock in default.conf is correct, DavLock will be created automatically when the container starts, and there is no need to create it manually under normal circumstances.

So just change the first line of the "default.conf" file to "DavLockDB ${APACHE_LOCK_DIR}/DAVLock".
![image](https://user-images.githubusercontent.com/31540107/126612209-535f7ee9-1663-4051-979c-0a225f5965db.png)

**Comment by binfalse** [comment]
super cool! thank you :)

would you create a pull request?
